name: bridge_deploy

on:
  workflow_dispatch:
    inputs:
      boot_config:
        description: 'Boot Config File'
        required: false
        type: string
      key_to_boot:
        description: 'Key to Boot'
        required: false
        type: string

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Deploy
        env:
          XMTP_BRIDGE_DROPLET_PK: ${{ secrets.XMTP_BRIDGE_DROPLET_PK }}
          XMTP_BRIDGE_DROPLET_IP: ${{ secrets.XMTP_BRIDGE_DROPLET_IP }}
          BOOT_CONFIG_B64: ${{ inputs.boot_config }}
          _KEY_TO_BOOT: ${{ inputs.key_to_boot }}
          _SENTRY_DSN: ${{ secrets.SENTRY_DSN }}
        run: |
          ./shell/bridge.deploy.sh
